matrix:
- name: markdown
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
      - a
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
      - whitelist.txt
    output: .pyspelling_en.dict
  sources:
  - 'docs/**/*.md'
